// Code generated by "stringer -type=LexingTokenType"; DO NOT EDIT.

package symbols

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IgnoreToken-0]
	_ = x[NewLineToken-1]
	_ = x[WhitespaceToken-2]
	_ = x[NumberToken-3]
	_ = x[LetterToken-4]
	_ = x[IdentifierKeyToken-5]
	_ = x[IdentifierValueToken-6]
	_ = x[VariableReferenceToken-7]
	_ = x[OpenCurlyBracketToken-8]
	_ = x[CloseCurlyBracketToken-9]
	_ = x[AssignmentOperatorToken-10]
	_ = x[ChainOperatorToken-11]
	_ = x[GreaterThanOrEqualOperatorToken-12]
	_ = x[LessThanOrEqualOperatorToken-13]
	_ = x[GreaterThanOperatorToken-14]
	_ = x[LessThanOperatorToken-15]
	_ = x[ExactMatchOperatorToken-16]
	_ = x[StyleCombineToken-17]
	_ = x[RuleStrictnessIndicatorToken-18]
	_ = x[MetadataKeywordToken-19]
	_ = x[NameKeywordToken-20]
	_ = x[VersionKeywordToken-21]
	_ = x[StrictnessKeywordToken-22]
	_ = x[AllKeywordToken-23]
	_ = x[SoftKeywordToken-24]
	_ = x[SemiStrictKeywordToken-25]
	_ = x[StrictKeywordToken-26]
	_ = x[SuperStrictKeywordToken-27]
	_ = x[VariableKeywordToken-28]
	_ = x[SectionConditionsKeywordToken-29]
	_ = x[ConditionAssignmentKeywordToken-30]
	_ = x[ConditionKeywordToken-31]
	_ = x[SectionKeywordToken-32]
	_ = x[DescriptionAssignmentKeywordToken-33]
	_ = x[RuleKeywordToken-34]
	_ = x[DotToken-35]
}

const _LexingTokenType_name = "IgnoreTokenNewLineTokenWhitespaceTokenNumberTokenLetterTokenIdentifierKeyTokenIdentifierValueTokenVariableReferenceTokenOpenCurlyBracketTokenCloseCurlyBracketTokenAssignmentOperatorTokenChainOperatorTokenGreaterThanOrEqualOperatorTokenLessThanOrEqualOperatorTokenGreaterThanOperatorTokenLessThanOperatorTokenExactMatchOperatorTokenStyleCombineTokenRuleStrictnessIndicatorTokenMetadataKeywordTokenNameKeywordTokenVersionKeywordTokenStrictnessKeywordTokenAllKeywordTokenSoftKeywordTokenSemiStrictKeywordTokenStrictKeywordTokenSuperStrictKeywordTokenVariableKeywordTokenSectionConditionsKeywordTokenConditionAssignmentKeywordTokenConditionKeywordTokenSectionKeywordTokenDescriptionAssignmentKeywordTokenRuleKeywordTokenDotToken"

var _LexingTokenType_index = [...]uint16{0, 11, 23, 38, 49, 60, 78, 98, 120, 141, 163, 186, 204, 235, 263, 287, 308, 331, 348, 376, 396, 412, 431, 453, 468, 484, 506, 524, 547, 567, 596, 627, 648, 667, 700, 716, 724}

func (i LexingTokenType) String() string {
	if i < 0 || i >= LexingTokenType(len(_LexingTokenType_index)-1) {
		return "LexingTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LexingTokenType_name[_LexingTokenType_index[i]:_LexingTokenType_index[i+1]]
}
