// Code generated by "stringer -type=LexingTokenType"; DO NOT EDIT.

package symbols

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IgnoreToken-0]
	_ = x[NewLineToken-1]
	_ = x[WhitespaceToken-2]
	_ = x[DigitToken-3]
	_ = x[LetterToken-4]
	_ = x[IdentifierKeyToken-5]
	_ = x[IdentifierValueToken-6]
	_ = x[VariableReferenceToken-7]
	_ = x[OpenCurlyBracketToken-8]
	_ = x[CloseCurlyBracketToken-9]
	_ = x[AssignmentOperatorToken-10]
	_ = x[ChainOperatorToken-11]
	_ = x[GreaterThanOrEqualOperatorToken-12]
	_ = x[LessThanOrEqualOperatorToken-13]
	_ = x[GreaterThanOperatorToken-14]
	_ = x[LessThanOperatorToken-15]
	_ = x[ExactMatchOperatorToken-16]
	_ = x[MetadataKeywordToken-17]
	_ = x[NameKeywordToken-18]
	_ = x[VersionKeywordToken-19]
	_ = x[StrictnessKeywordToken-20]
	_ = x[AllKeywordToken-21]
	_ = x[SoftKeywordToken-22]
	_ = x[SemiStrictKeywordToken-23]
	_ = x[StrictKeywordToken-24]
	_ = x[SuperStrictKeywordToken-25]
	_ = x[VariableKeywordToken-26]
	_ = x[SectionConditionsKeywordToken-27]
	_ = x[ConditionAssignmentKeywordToken-28]
	_ = x[ConditionKeywordToken-29]
	_ = x[SectionKeywordToken-30]
	_ = x[DotToken-31]
}

const _LexingTokenType_name = "IgnoreTokenNewLineTokenWhitespaceTokenDigitTokenLetterTokenIdentifierKeyTokenIdentifierValueTokenVariableReferenceTokenOpenCurlyBracketTokenCloseCurlyBracketTokenAssignmentOperatorTokenChainOperatorTokenGreaterThanOrEqualOperatorTokenLessThanOrEqualOperatorTokenGreaterThanOperatorTokenLessThanOperatorTokenExactMatchOperatorTokenMetadataKeywordTokenNameKeywordTokenVersionKeywordTokenStrictnessKeywordTokenAllKeywordTokenSoftKeywordTokenSemiStrictKeywordTokenStrictKeywordTokenSuperStrictKeywordTokenVariableKeywordTokenSectionConditionsKeywordTokenConditionAssignmentKeywordTokenConditionKeywordTokenSectionKeywordTokenDotToken"

var _LexingTokenType_index = [...]uint16{0, 11, 23, 38, 48, 59, 77, 97, 119, 140, 162, 185, 203, 234, 262, 286, 307, 330, 350, 366, 385, 407, 422, 438, 460, 478, 501, 521, 550, 581, 602, 621, 629}

func (i LexingTokenType) String() string {
	if i < 0 || i >= LexingTokenType(len(_LexingTokenType_index)-1) {
		return "LexingTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LexingTokenType_name[_LexingTokenType_index[i]:_LexingTokenType_index[i+1]]
}
